### ISSUE TITLE
VLC notification? menu empty

### ISSUE THREAD

**Issue by pixelr0** [ubuntu/snappy-playpen#154]
VLC notification? menu empty
snapd (2.0.10)
VLC revision 9 

screenshot with the empty menu http://i.imgur.com/lZdo2tP.png

**Comment by dplanella** [comment]
Thanks @pixelr0 for the report. This is due to these known isses in snappy, which will hopefully be addressed in the upcoming weeks:

- https://bugs.launchpad.net/snappy/+bug/1600136
- https://bugs.launchpad.net/snappy/+bug/1600138
- https://bugs.launchpad.net/snappy/+bug/1600140

As it's not directly related to the playpen, I'll close the issue for now and I'll suggest you to subscribe to the snappy bugs to track the status.

Thanks!

**Comment by pixelr0** [comment]
thanks david :D already subscribed
